import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Hero from '@/components/Hero'
import Projects from '@/components/sections/Projects'
import Contact from '@/components/sections/Contact'
import Footer from '@/components/sections/Footer'
import ControlSlashModal from '@/components/dust/ControlSlashModal'
import HotkeysInit from '@/components/HotkeysInit'

export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <Hero />
      </main>
      <Projects />
      <Contact />
      <Footer />

      <ControlSlashModal />
      <HotkeysInit />
    </>
  );
}